spring:
  datasource:
#    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/spring3_template?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      data-source-class-name: com.zaxxer.hikari.HikariDataSource
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring3_template?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: consen3464
  data:
    redis:
      host: 172.29.134.208
      port: 6379
      database: 15
      password:
      connect-timeout: 10s
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
